color-scheme: auto
description: Feira de Jogos - Instituto Federal de Santa Catarina campus São José
jekyll-spaceship:
  processors:
    - mermaid-processor
  mermaid-processor:
    mode: default
    css:
      class: mermaid
    syntax:
      code: 'mermaid'
      custom: ['@startmermaid', '@endmermaid']
    config:
      theme: default
    src: https://mermaid.ink/svg/
plugins:
  - jekyll-remote-theme
  - jekyll-spaceship
remote_theme: BDHU/minimalist
repository: feira-de-jogos/feira-de-jogos
source: docs/
title: Feira de Jogos
