server {
  listen 80;

  return 301 https://$host$request_uri;
}

ssl_protocols TLSv1.3;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
ssl_prefer_server_ciphers off;
ssl_session_cache shared:SSL:10m;
ssl_session_timeout 10m;
ssl_session_tickets off;
ssl_certificate /etc/nginx/fullchain.pem;
ssl_certificate_key /etc/nginx/privkey.pem;
add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload" always;

http2 on;

http3 on;
http3_hq on;
quic_retry on;
ssl_early_data on;
quic_gso on;
add_header Alt-Svc 'h3=":8443"; ma=86400';

resolver 1.1.1.1;

server {
  server_name feira-de-jogos.dev.br;

  listen 443 ssl;
  listen 443 quic reuseport;

  location / {
    add_header X-Content-Type-Options nosniff;
    add_header Content-Security-Policy "object-src 'none'; base-uri 'none'; frame-ancestors 'self';";
    add_header Content-Security-Policy "frame-ancestors 'self';";

    root /frontend;
    try_files $uri $uri/ =404;

    # Retirado de: https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html
    location ~ .+\.(data|symbols\.json)\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/octet-stream;
    }

    location ~ .+\.js\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/javascript;
    }

    location ~ .+\.wasm\.br$ {
      gzip off;
      add_header Content-Encoding br;
      default_type application/wasm;
    }

    location ~ .+\.(data|symbols\.json)\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/gzip;
    }

    location ~ .+\.js\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/javascript;
    }

    location ~ .+\.wasm\.gz$ {
      gzip off;
      add_header Content-Encoding gzip;
      default_type application/wasm;
    }
  }

  location /api/v2/ {
    proxy_pass http://rest-api:3000/api/v2/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }

  location /adcipt20232-Projeto-PATO-Alem-das-Montanhas/ {
    alias /jogos/adcipt20232-Projeto-PATO-Alem-das-Montanhas/cliente/;
  }

  location /adcieqipt20241-huntersofancientbeasts-jogo/ {
    alias /jogos/adcieqipt20241-huntersofancientbeasts-jogo/cliente/;
  }

  location /adcieqipt20241-Karolzinha-e-Loulou-avadakedavra/ {
    alias /jogos/adcieqipt20241-Karolzinha-e-Loulou-avadakedavra/cliente/;
  }

  location /adcieqipt20241-nlentertainment-jogo/ {
    alias /jogos/adcieqipt20241-nlentertainment-jogo/cliente/;
  }

  location /adcieqipt20241-Thuthu-e-Aninha-jogo/ {
    alias /jogos/adcieqipt20241-Thuthu-e-Aninha-jogo/cliente/;
  }

  location /adcieqipt20241-vimdoalegrete-jogo/ {
    alias /jogos/adcieqipt20241-vimdoalegrete-jogo/cliente/;
  }

  location /adcieqipt20241-vitorhlmm-Jogo/ {
    alias /jogos/adcieqipt20241-vitorhlmm-Jogo/cliente/;
  }

  location /rescue-run/ {
    alias /jogos/rescue-run/cliente/;
  }
}

server {
  server_name mqtt.feira-de-jogos.dev.br;

  listen 443 ssl;
  listen 443 quic;

  location / {
    proxy_pass http://mqtt-broker:8080/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}

server {
  server_name grafana.feira-de-jogos.dev.br;

  listen 443 ssl;
  listen 443 quic;

  location / {
    proxy_pass http://grafana:3000/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}


server {
  server_name tsdb.feira-de-jogos.dev.br;

  listen 443 ssl;
  listen 443 quic;

  location / {
    proxy_pass http://tsdb:8086/;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $host;
  }
}
